name: dgarment
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=3_kmp_llvm
  - aom=3.9.1=hac33072_0
  - attr=2.5.1=h166bdaf_1
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cpython=3.13.5=py313hd8ed1ab_102
  - cuda-crt-tools=12.9.86=ha770c72_2
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-cuobjdump=12.9.82=hbd13f7d_0
  - cuda-cupti=12.9.79=h9ab20c4_0
  - cuda-nvcc-tools=12.9.86=he02047a_2
  - cuda-nvdisasm=12.9.88=hbd13f7d_0
  - cuda-nvrtc=12.9.86=h5888daf_0
  - cuda-nvtx=12.9.79=h5888daf_0
  - cuda-nvvm-tools=12.9.86=h4bc722e_2
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.1.4=hbcb9cd8_1
  - cusparselt=0.7.0.0=hcd2ec93_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dav1d=1.2.1=hd590300_0
  - freetype=2.13.3=ha770c72_1
  - fsspec=2025.7.0=pyhd8ed1ab_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py313h11186cd_0
  - icu=75.1=he02047a_0
  - iopath=0.1.10=pyhd8ed1ab_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libavif16=1.3.0=h766b0b6_0
  - libblas=3.9.0=32_h59b9bed_openblas
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=32_he106b2a_openblas
  - libcublas=12.9.1.4=h9ab20c4_0
  - libcudnn=9.10.1.4=hf7e9902_1
  - libcudnn-dev=9.10.1.4=h58dd1b1_1
  - libcudss=0.6.0.5=h58dd1b1_0
  - libcudss0=0.4.0.2=he55f5cd_2
  - libcufft=11.4.1.4=h5888daf_0
  - libcufile=1.14.1.1=ha8da6e3_0
  - libcurand=10.3.10.19=h9ab20c4_0
  - libcusolver=11.7.5.82=h9ab20c4_1
  - libcusparse=12.5.10.65=h5888daf_1
  - libde265=1.0.15=h00ab1b0_0
  - libdeflate=1.24=h86f0d12_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgfortran=15.1.0=h69a702a_4
  - libgfortran5=15.1.0=hcea5267_4
  - libgomp=15.1.0=h767d61c_4
  - libgpg-error=1.55=h3f2d84a_0
  - libheif=1.19.7=gpl_hc18d805_100
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - libllvm20=20.1.8=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libmagma=2.9.0=h9918c94_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnvjitlink=12.9.86=h5888daf_1
  - libnvjpeg=12.4.0.76=h5888daf_0
  - libopenblas=0.3.30=pthreads_h94d23a6_1
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=6.31.1=h9ef548d_1
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libsystemd0=257.7=h4e0b6ca_0
  - libtiff=4.7.0=hf01ce69_5
  - libtorch=2.7.1=cuda129_generic_h79bc694_203
  - libudev1=257.7=hbe16f8c_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=20.1.8=h4922eb0_1
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.2=py313h8060acc_1
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - nccl=2.27.7.1=h49b9d9a_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.5=pyhe01879c_0
  - nomkl=1.0=h5ca1d4c_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.1=h7b32b05_0
  - optree=0.17.0=py313h7037e92_0
  - portalocker=3.2.0=py313h78bf25f_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pybind11=3.0.0=pyh9380348_1
  - pybind11-global=3.0.0=pyhf748d72_1
  - python=3.13.2=hf636f53_101_cp313
  - python_abi=3.13=8_cp313
  - pytorch=2.7.1=cuda129_generic_py313_h8eaeedc_203
  - pytorch3d=0.7.7=cuda129py313hdcc24bf_9
  - pyyaml=6.0.2=py313h8060acc_2
  - rav1e=0.7.1=h8fae777_3
  - rdma-core=58.0=h5888daf_0
  - readline=8.2=h8c095d6_2
  - sleef=3.8=h1b44611_0
  - svt-av1=3.0.2=h5888daf_0
  - tabulate=0.9.0=pyhd8ed1ab_2
  - termcolor=3.1.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - torchvision-extra-decoders=0.0.2=py313hf1e760e_3
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - x265=3.5=h924138e_3
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - yacs=0.1.8=pyh29332c3_2
  - yaml=0.2.5=h280c20c_3
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - accelerate==1.4.0
      - asttokens==3.0.0
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - debugpy==1.8.13
      - decorator==5.2.1
      - diffusers==0.34.0
      - executing==2.2.0
      - filelock==3.13.1
      - fonttools==4.56.0
      - freetype-py==2.5.1
      - hf-xet==1.1.5
      - huggingface-hub==0.34.3
      - human-body-prior==2.2.2.0
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - ipykernel==6.29.5
      - ipython==9.0.2
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.5
      - jedi==0.19.2
      - jinja2==3.1.4
      - json-tricks==3.17.3
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mesh-intersection==0.1.0
      - meshlib==3.0.5.215
      - nest-asyncio==1.6.0
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.0.0
      - pip==25.2
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.50
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyglet==1.5.31
      - pygments==2.19.1
      - pyopengl==3.1.9
      - pyparsing==3.2.1
      - pyrender==0.1.45
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyzmq==26.2.1
      - regex==2025.7.34
      - requests==2.32.4
      - robust-loss-pytorch==0.0.2
      - safetensors==0.5.3
      - scipy==1.15.2
      - setuptools==70.2.0
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.13.1
      - tokenizers==0.21.4
      - torch==2.6.0+cu126
      - torch-dct==0.1.6
      - torchaudio==2.6.0+cu126
      - torchgeometry==0.1.2
      - torchvision==0.21.0+cu126
      - tornado==6.4.2
      - traitlets==5.14.3
      - transformers==4.50.0.dev0
      - trimesh==4.6.4
      - triton==3.2.0
      - tzdata==2025.1
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - widgetsnbextension==4.0.13
      - zipp==3.21.0
